# main
server:
  port: 8080
  address: localhost

# database
spring:
  datasource:
    url: @db.url@
    username: @db.user@
    password: @db.password@

# logging
logging:
  level:
    org:
      jooq:
        Constants: ERROR
